"""Update bussines_hours: opnning_time and clousing_time2

Revision ID: 0b91c11bd368
Revises: f1c536229d83
Create Date: 2023-05-22 22:00:47.316271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b91c11bd368'
down_revision = 'f1c536229d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
