"""added assited_by in reservation assignment

Revision ID: 13750bb1eaed
Revises: 3b65a2f09a75
Create Date: 2023-05-25 15:11:46.168791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13750bb1eaed'
down_revision = '3b65a2f09a75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_assignment', sa.Column('assisted_by', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation_assignment', 'assisted_by')
    # ### end Alembic commands ###
