"""changes in customer

Revision ID: 14e549093e09
Revises: 2a63a40b8cc4
Create Date: 2023-04-09 10:18:21.536136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e549093e09'
down_revision = '2a63a40b8cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###
