"""the notification type field was added

Revision ID: 17a2e7a545b5
Revises: 7a344904b341
Create Date: 2023-04-12 16:36:12.073174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a2e7a545b5'
down_revision = '7a344904b341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('notification_type', sa.Enum('Whatsapp', 'Email'), nullable=True))
    op.drop_column('notification', 'notification_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_type', mysql.ENUM('Whatsapp', 'Email', collation='utf8mb4_spanish2_ci'), nullable=True))
    op.drop_column('customer', 'notification_type')
    # ### end Alembic commands ###
