"""Table Change ParkingSpot coordinate and status

Revision ID: 1b984359d781
Revises: fe5bf1996ac9
Create Date: 2023-04-23 23:36:09.323793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b984359d781'
down_revision = 'fe5bf1996ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('coordinate', sa.Text(), nullable=True))
    op.add_column('parking_spot', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('parking_spot', 'state')
    op.drop_column('parking_spot', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('coordinates', sa.BLOB(), nullable=True))
    op.add_column('parking_spot', sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('parking_spot', 'status')
    op.drop_column('parking_spot', 'coordinate')
    # ### end Alembic commands ###
