"""new table weekday

Revision ID: 1d49e4db9ba5
Revises: c31b10708f36
Create Date: 2023-04-17 20:28:23.274015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d49e4db9ba5'
down_revision = 'c31b10708f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
