"""add role permissions

Revision ID: 1e06c1fd8b30
Revises: 83d318b0a191
Create Date: 2023-04-10 17:20:49.580343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e06c1fd8b30'
down_revision = '83d318b0a191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
