"""modify parking-spot

Revision ID: 220ef34a7a6e
Revises: 4d64eeff1e9f
Create Date: 2023-05-03 16:10:53.003366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '220ef34a7a6e'
down_revision = '4d64eeff1e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('type', sa.Enum('Previlegiado', 'Regular', 'Común'), nullable=False))
    op.drop_column('parking_spot', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('tipo', mysql.ENUM('Previlegiado', 'Regular', 'Común', collation='utf8mb4_spanish2_ci'), nullable=False))
    op.drop_column('parking_spot', 'type')
    # ### end Alembic commands ###
