"""new table: parking_type

Revision ID: 26bc91fa4f67
Revises: dbbad27d0689
Create Date: 2023-06-11 10:38:42.077002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26bc91fa4f67'
down_revision = 'dbbad27d0689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('type_spot', sa.String(length=4), nullable=True))
    op.create_foreign_key(None, 'parking_spot', 'parking_type', ['type_spot'], ['id_spot_type'])
    op.drop_column('parking_spot', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('type', mysql.ENUM('Previlegiado', 'Regular', 'Común'), nullable=True))
    op.drop_constraint(None, 'parking_spot', type_='foreignkey')
    op.drop_column('parking_spot', 'type_spot')
    # ### end Alembic commands ###
