"""name changes

Revision ID: 2a63a40b8cc4
Revises: c0a4b12fcc04
Create Date: 2023-04-07 16:12:54.339111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a63a40b8cc4'
down_revision = 'c0a4b12fcc04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('openning_time', sa.DateTime(), nullable=False))
    op.drop_column('business_hours', 'opnning_time')
    op.add_column('claims', sa.Column('id_claim', sa.String(length=4), nullable=False))
    op.add_column('claims', sa.Column('author', sa.String(length=4), nullable=True))
    op.drop_constraint('claims_ibfk_1', 'claims', type_='foreignkey')
    op.create_foreign_key(None, 'claims', 'customer', ['author'], ['id_customer'])
    op.drop_column('claims', 'id_claims')
    op.drop_column('claims', 'performs')
    op.add_column('customer', sa.Column('registered_by', sa.String(length=4), nullable=True))
    op.drop_constraint('customer_ibfk_2', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'administrator', ['registered_by'], ['id_administrator'])
    op.drop_column('customer', 'register_by')
    op.add_column('employee', sa.Column('registered_by', sa.String(length=4), nullable=True))
    op.drop_constraint('employee_ibfk_2', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'administrator', ['registered_by'], ['id_administrator'])
    op.drop_column('employee', 'register_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('register_by', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_2', 'employee', 'administrator', ['register_by'], ['id_administrator'])
    op.drop_column('employee', 'registered_by')
    op.add_column('customer', sa.Column('register_by', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_ibfk_2', 'customer', 'administrator', ['register_by'], ['id_administrator'])
    op.drop_column('customer', 'registered_by')
    op.add_column('claims', sa.Column('performs', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.add_column('claims', sa.Column('id_claims', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=False))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.create_foreign_key('claims_ibfk_1', 'claims', 'customer', ['performs'], ['id_customer'])
    op.drop_column('claims', 'author')
    op.drop_column('claims', 'id_claim')
    op.add_column('business_hours', sa.Column('opnning_time', mysql.DATETIME(), nullable=False))
    op.drop_column('business_hours', 'openning_time')
    # ### end Alembic commands ###
