"""db

Revision ID: 2e9cf523f2bc
Revises: 
Create Date: 2023-06-13 21:05:09.047069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e9cf523f2bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_type',
    sa.Column('id_spot_type', sa.String(length=4), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_spot_type')
    )
    op.create_foreign_key(None, 'parking_spot', 'parking_type', ['type_spot'], ['id_spot_type'])
    op.drop_column('parking_spot', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('type', mysql.ENUM('Previlegiado', 'Regular', 'Común'), nullable=False))
    op.drop_constraint(None, 'parking_spot', type_='foreignkey')
    op.drop_table('parking_type')
    # ### end Alembic commands ###
