"""db update

Revision ID: 2fb5c41a0a8a
Revises: ca870c0a8cae
Create Date: 2023-04-25 01:34:30.693631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb5c41a0a8a'
down_revision = 'ca870c0a8cae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
