"""modified business and hourlyrate

Revision ID: 3b65a2f09a75
Revises: 7da13a9fdf67
Create Date: 2023-05-24 21:04:09.761522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b65a2f09a75'
down_revision = '7da13a9fdf67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourly_rate', sa.Column('type', sa.Enum('Previlegiado', 'Regular', 'Común'), nullable=False))
    op.drop_constraint('parking_spot_ibfk_1', 'parking_spot', type_='foreignkey')
    op.drop_column('parking_spot', 'id_hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('id_hour', mysql.VARCHAR(length=4), nullable=True))
    op.create_foreign_key('parking_spot_ibfk_1', 'parking_spot', 'business_hours', ['id_hour'], ['id_hour'])
    op.drop_column('hourly_rate', 'type')
    # ### end Alembic commands ###
