"""changes tables

Revision ID: 48e1eefc14b5
Revises: 14e549093e09
Create Date: 2023-04-09 14:28:58.474102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e1eefc14b5'
down_revision = '14e549093e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('id_customer', sa.String(length=4), nullable=True))
    op.drop_constraint('vehicle_ibfk_1', 'vehicle', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'customer', ['id_customer'], ['id_customer'])
    op.drop_column('vehicle', 'id_employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('id_employee', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.create_foreign_key('vehicle_ibfk_1', 'vehicle', 'customer', ['id_employee'], ['id_customer'])
    op.drop_column('vehicle', 'id_customer')
    # ### end Alembic commands ###
