"""add role permissions

Revision ID: 4d26e56178f5
Revises: 1e06c1fd8b30
Create Date: 2023-04-10 18:17:36.791073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d26e56178f5'
down_revision = '1e06c1fd8b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
