"""create table assignmentassignment_rate

Revision ID: 4d64eeff1e9f
Revises: 6d16bdf725b7
Create Date: 2023-05-03 15:57:12.369681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d64eeff1e9f'
down_revision = '6d16bdf725b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourly_rate', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('hourly_rate', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('hourly_rate', 'week_day')
    op.add_column('parking_spot', sa.Column('tipo', sa.Enum('Previlegiado', 'Regular', 'Común'), nullable=False))
    op.drop_constraint('parking_spot_ibfk_2', 'parking_spot', type_='foreignkey')
    op.drop_column('parking_spot', 'price')
    op.add_column('reservation_assignment', sa.Column('id_assignment_rate', sa.String(length=4), nullable=True))
    op.create_foreign_key(None, 'reservation_assignment', 'assignment_rate', ['id_assignment_rate'], ['id_assignment_rate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation_assignment', type_='foreignkey')
    op.drop_column('reservation_assignment', 'id_assignment_rate')
    op.add_column('parking_spot', sa.Column('price', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.create_foreign_key('parking_spot_ibfk_2', 'parking_spot', 'hourly_rate', ['price'], ['id_price'])
    op.drop_column('parking_spot', 'tipo')
    op.add_column('hourly_rate', sa.Column('week_day', mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', collation='utf8mb4_spanish2_ci'), nullable=False))
    op.drop_column('hourly_rate', 'end_date')
    op.drop_column('hourly_rate', 'start_date')
    # ### end Alembic commands ###
