"""Update pay=Column customer and ForeingKey:reservation

Revision ID: 4fcce83c3345
Revises: a0ddcbd28acd
Create Date: 2023-05-14 20:27:57.110763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fcce83c3345'
down_revision = 'a0ddcbd28acd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay', sa.Column('reservation', sa.String(length=4), nullable=True))
    op.drop_constraint('pay_ibfk_1', 'pay', type_='foreignkey')
    op.create_foreign_key(None, 'pay', 'reservation', ['reservation'], ['id_reservation'])
    op.drop_column('pay', 'employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay', sa.Column('employee', mysql.VARCHAR(length=4), nullable=True))
    op.drop_constraint(None, 'pay', type_='foreignkey')
    op.create_foreign_key('pay_ibfk_1', 'pay', 'customer', ['employee'], ['id_customer'])
    op.drop_column('pay', 'reservation')
    # ### end Alembic commands ###
