"""Changes in business_hour

Revision ID: 6773ebd35c95
Revises: 7828a263972a
Create Date: 2023-04-22 16:05:24.503599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6773ebd35c95'
down_revision = '7828a263972a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
