"""modify table user: user_type

Revision ID: 6b691bc02a6e
Revises: 865e81272210
Create Date: 2023-05-07 09:50:38.984345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b691bc02a6e'
down_revision = '865e81272210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
