"""create table reservation_assignment3

Revision ID: 6d16bdf725b7
Revises: acd413f551a2
Create Date: 2023-05-01 16:33:30.098752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d16bdf725b7'
down_revision = 'acd413f551a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_assignment',
    sa.Column('id_assignment', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('Reserved', 'Occupied', 'Available'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id_spot', sa.String(length=4), nullable=True),
    sa.Column('id_reservation', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservation.id_reservation'], ),
    sa.ForeignKeyConstraint(['id_spot'], ['parking_spot.id_spot'], ),
    sa.PrimaryKeyConstraint('id_assignment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_assignment')
    # ### end Alembic commands ###
