"""Table BussinesHours3

Revision ID: 6e5c5e5442ce
Revises: 3cd1a981fb94
Create Date: 2023-04-23 08:04:54.200401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e5c5e5442ce'
down_revision = '3cd1a981fb94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('days', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='day_of_week_enum'), nullable=False))
    op.drop_column('business_hours', 'week_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('week_day', mysql.DATETIME(), nullable=False))
    op.drop_column('business_hours', 'days')
    # ### end Alembic commands ###
