"""updated reservation: foreingkey=id_price

Revision ID: 75f03d764d47
Revises: 4fcce83c3345
Create Date: 2023-05-15 16:06:39.371715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f03d764d47'
down_revision = '4fcce83c3345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('id_price', sa.String(length=4), nullable=True))
    op.create_foreign_key(None, 'reservation', 'hourly_rate', ['id_price'], ['id_price'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'id_price')
    # ### end Alembic commands ###
