"""Changes in business_hours

Revision ID: 7828a263972a
Revises: ee81742cfc48
Create Date: 2023-04-22 15:54:05.650520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7828a263972a'
down_revision = 'ee81742cfc48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekday',
    sa.Column('id_day', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=False),
    sa.Column('day', mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('id_reservation', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservation.id_reservation'], name='weekday_ibfk_1'),
    sa.PrimaryKeyConstraint('id_day'),
    mysql_collate='utf8mb4_spanish2_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
