"""Database system-parking

Revision ID: 865e81272210
Revises: 
Create Date: 2023-05-07 09:38:26.626383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865e81272210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id_hour', sa.String(length=4), nullable=False),
    sa.Column('days', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='day_of_week_enum'), nullable=False),
    sa.Column('openning_time', sa.DateTime(), nullable=False),
    sa.Column('clousing_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_hour')
    )
    op.create_table('hourly_rate',
    sa.Column('id_price', sa.String(length=4), nullable=False),
    sa.Column('hourly_rate', sa.Float(precision=5), nullable=False),
    sa.Column('daily_rate', sa.Float(precision=5), nullable=False),
    sa.Column('weekly_rate', sa.Float(precision=5), nullable=False),
    sa.Column('monthly_rate', sa.Float(precision=5), nullable=False),
    sa.Column('annual_rate', sa.Float(precision=5), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_price')
    )
    op.create_table('permission',
    sa.Column('id_permission', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_permission')
    )
    op.create_table('role',
    sa.Column('id_role', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('parking_spot',
    sa.Column('id_spot', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=4), nullable=False),
    sa.Column('coordinate', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('Previlegiado', 'Regular', 'Común'), nullable=False),
    sa.Column('id_hour', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_hour'], ['business_hours.id_hour'], ),
    sa.PrimaryKeyConstraint('id_spot')
    )
    op.create_table('role_permission',
    sa.Column('id_role_permission', sa.String(length=4), nullable=False),
    sa.Column('id_role', sa.String(length=4), nullable=True),
    sa.Column('id_permission', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id_permission'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_role_permission')
    )
    op.create_table('user',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=True),
    sa.Column('user_type', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('administrator',
    sa.Column('id_administrator', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_administrator')
    )
    op.create_table('assignment_rate',
    sa.Column('id_assignment_rate', sa.String(length=4), nullable=False),
    sa.Column('id_spot', sa.String(length=4), nullable=True),
    sa.Column('id_price', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_price'], ['hourly_rate.id_price'], ),
    sa.ForeignKeyConstraint(['id_spot'], ['parking_spot.id_spot'], ),
    sa.PrimaryKeyConstraint('id_assignment_rate')
    )
    op.create_table('customer',
    sa.Column('id_customer', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('notification_type', sa.Enum('Whatsapp', 'Email'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_customer')
    )
    op.create_table('user_permission',
    sa.Column('id_user_permission', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_permission', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id_permission'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_permission')
    )
    op.create_table('claims',
    sa.Column('id_claim', sa.String(length=4), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('request', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['customer.id_customer'], ),
    sa.PrimaryKeyConstraint('id_claim')
    )
    op.create_table('employee',
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_employee', sa.String(length=4), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=False),
    sa.Column('salary', sa.Float(precision=5), nullable=False),
    sa.Column('registered_by', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['administrator.id_administrator'], ),
    sa.PrimaryKeyConstraint('id_employee')
    )
    op.create_table('pay',
    sa.Column('id_pay', sa.String(length=4), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_time', sa.Time(), nullable=False),
    sa.Column('amount', sa.Float(precision=5), nullable=False),
    sa.Column('employee', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['employee'], ['customer.id_customer'], ),
    sa.PrimaryKeyConstraint('id_pay')
    )
    op.create_table('reservation',
    sa.Column('id_reservation', sa.String(length=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id_customer', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id_customer'], ),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    op.create_table('vehicle',
    sa.Column('id_vehicle', sa.String(length=4), nullable=False),
    sa.Column('license_plate', sa.String(length=8), nullable=False),
    sa.Column('vehicle_type', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=15), nullable=False),
    sa.Column('photo', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('id_customer', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id_customer'], ),
    sa.PrimaryKeyConstraint('id_vehicle')
    )
    op.create_table('notification',
    sa.Column('id_notication', sa.String(length=4), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('id_employee', sa.String(length=4), nullable=True),
    sa.Column('id_customer', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id_customer'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.PrimaryKeyConstraint('id_notication')
    )
    op.create_table('reservation_assignment',
    sa.Column('id_assignment', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('Reserved', 'Occupied', 'Available'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id_spot', sa.String(length=4), nullable=True),
    sa.Column('id_reservation', sa.String(length=4), nullable=True),
    sa.Column('id_assignment_rate', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_assignment_rate'], ['assignment_rate.id_assignment_rate'], ),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservation.id_reservation'], ),
    sa.ForeignKeyConstraint(['id_spot'], ['parking_spot.id_spot'], ),
    sa.PrimaryKeyConstraint('id_assignment')
    )
    op.create_table('weekday',
    sa.Column('id_day', sa.String(length=4), nullable=False),
    sa.Column('day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='day_of_week_enum'), nullable=False),
    sa.Column('id_reservation', sa.String(length=4), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservation.id_reservation'], ),
    sa.PrimaryKeyConstraint('id_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekday')
    op.drop_table('reservation_assignment')
    op.drop_table('notification')
    op.drop_table('vehicle')
    op.drop_table('reservation')
    op.drop_table('pay')
    op.drop_table('employee')
    op.drop_table('claims')
    op.drop_table('user_permission')
    op.drop_table('customer')
    op.drop_table('assignment_rate')
    op.drop_table('administrator')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('parking_spot')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('hourly_rate')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
