"""Update bussines_hours: opnning_time and clousing_time3

Revision ID: 897e754b71c7
Revises: 0b91c11bd368
Create Date: 2023-05-22 23:34:45.097990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897e754b71c7'
down_revision = '0b91c11bd368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
