"""the notification type field was added 

Revision ID: 9ac65f3704ad
Revises: 17a2e7a545b5
Create Date: 2023-04-12 21:09:51.444525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ac65f3704ad'
down_revision = '17a2e7a545b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'notification_type',
               existing_type=mysql.ENUM('Whatsapp', 'Email', collation='utf8mb4_spanish2_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'notification_type',
               existing_type=mysql.ENUM('Whatsapp', 'Email', collation='utf8mb4_spanish2_ci'),
               nullable=True)
    # ### end Alembic commands ###
