"""changes in table weekday

Revision ID: ab0c14a518cd
Revises: 1d49e4db9ba5
Create Date: 2023-04-17 20:42:15.527767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab0c14a518cd'
down_revision = '1d49e4db9ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'end_time')
    op.drop_column('reservation', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('start_time', mysql.TIME(), nullable=False))
    op.add_column('reservation', sa.Column('end_time', mysql.TIME(), nullable=False))
    # ### end Alembic commands ###
