"""create table reservation_assignment2

Revision ID: acd413f551a2
Revises: e1d55c31253e
Create Date: 2023-05-01 16:26:10.907773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd413f551a2'
down_revision = 'e1d55c31253e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
