"""changes in reservation 1

Revision ID: c31b10708f36
Revises: d3bb5e948032
Create Date: 2023-04-16 11:11:01.303435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31b10708f36'
down_revision = 'd3bb5e948032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
