"""changes in reservation

Revision ID: d3bb5e948032
Revises: 363d71261910
Create Date: 2023-04-16 10:12:52.633470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3bb5e948032'
down_revision = '363d71261910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('reservation', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.drop_column('reservation', 'use_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('use_duration', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=20), nullable=False))
    op.drop_column('reservation', 'create_at')
    op.drop_column('reservation', 'status')
    # ### end Alembic commands ###
