"""changes in table weekday 2

Revision ID: d6421ff0480f
Revises: ab0c14a518cd
Create Date: 2023-04-17 21:19:37.376285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6421ff0480f'
down_revision = 'ab0c14a518cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
