"""new changes Claim: status

Revision ID: dbbad27d0689
Revises: e595fa801ef3
Create Date: 2023-06-03 16:54:18.126532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbad27d0689'
down_revision = 'e595fa801ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'status')
    # ### end Alembic commands ###
