"""create table reservation_assignment

Revision ID: e1d55c31253e
Revises: 2fb5c41a0a8a
Create Date: 2023-05-01 16:24:01.401379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1d55c31253e'
down_revision = '2fb5c41a0a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_spot', 'status')
    op.drop_constraint('reservation_ibfk_2', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'status')
    op.drop_column('reservation', 'id_spot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('id_spot', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=True))
    op.add_column('reservation', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('reservation_ibfk_2', 'reservation', 'parking_spot', ['id_spot'], ['id_spot'])
    op.add_column('parking_spot', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
