"""new changes Claim: date

Revision ID: e595fa801ef3
Revises: 15eb9b64b58a
Create Date: 2023-06-03 15:53:21.606145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e595fa801ef3'
down_revision = '15eb9b64b58a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'registration_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'registration_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
