"""table weekday 3

Revision ID: ee81742cfc48
Revises: 43da80110092
Create Date: 2023-04-18 17:15:06.075975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee81742cfc48'
down_revision = '43da80110092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
