"""Update bussines_hours: opnning_time and clousing_time

Revision ID: f1c536229d83
Revises: 75f03d764d47
Create Date: 2023-05-22 21:56:42.944556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1c536229d83'
down_revision = '75f03d764d47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservation_assignment_ibfk_1', 'reservation_assignment', type_='foreignkey')
    op.drop_column('reservation_assignment', 'id_assignment_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_assignment', sa.Column('id_assignment_rate', mysql.VARCHAR(length=4), nullable=True))
    op.create_foreign_key('reservation_assignment_ibfk_1', 'reservation_assignment', 'assignment_rate', ['id_assignment_rate'], ['id_assignment_rate'])
    # ### end Alembic commands ###
