"""Table Change ParkingSpot coordinate

Revision ID: fe5bf1996ac9
Revises: 6e5c5e5442ce
Create Date: 2023-04-23 15:25:17.037459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe5bf1996ac9'
down_revision = '6e5c5e5442ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('coordinates', sa.BLOB(), nullable=True))
    op.drop_column('parking_spot', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spot', sa.Column('address', mysql.VARCHAR(collation='utf8mb4_spanish2_ci', length=4), nullable=False))
    op.drop_column('parking_spot', 'coordinates')
    # ### end Alembic commands ###
